# setup 
```{r}
library(tidyverse)
library(readr)
library(dplyr)
library(randomForest)
library(tidymodels)
library(skimr)
library(yardstick)
```

# loading data
```{r}
tester <- read.csv("data/daymet/fieldweather_final.csv")
```

# wrangling data
```{r}
field_data <- tester %>%
        mutate_if(is.character, as.factor)
```

# splitting data 
```{r}
set.seed(4595)
# Put 3/4 of the data into the training set 
data_split <- initial_split(field_data, ,strata = "str_emmean", prop = 0.75)

# Create data frames for the two sets:
train_data <- training(data_split)
test_data  <- testing(data_split)
```


# modeling
```{r}
rf_mod <- rand_forest(mode = "regression",  mtry = 3, trees = 1000)

# all temporal scales 
preds <- colnames(train_data)[grep("^srad_mean_growingseason", colnames(train_data)):ncol(train_data)]

rf_xy_fit <- 
  rf_mod %>%
  set_engine("randomForest") %>%
  fit_xy(
    x = train_data[, preds],
    y = log10(train_data$str_emmean)
  )

rf_xy_fit
#Mean of squared residuals: 0.00168 (OOB prediction error MSE )
#% Var explained: 22.61 R^2 (OOB needs to be higher)
```

# estimating performance
```{r}
#TRAINING
# Calculate evaluation metrics

```